# Generated by Django 4.0 on 2023-07-22 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reps', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rfps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('applicants', models.TextField()),
                ('status', models.CharField(choices=[('REVIEWED', 'Being Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Application Rejected')], default=('SUBMITTED', 'Submitted'), max_length=50)),
                ('concept_note', models.TextField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='auth.user')),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_applications', to='reps.representative')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='auth.user')),
                ('rfp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfp_applications', to='rfps.rfp')),
            ],
        ),
    ]
