# Generated by Django 4.0 on 2023-07-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_concept_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
