# Generated by Django 4.0 on 2023-07-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicants',
        ),
    ]
