# Generated by Django 4.0 on 2023-07-19 11:21

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('area_of_work', models.TextField(blank=True, max_length=500, null=True)),
                ('eligible_countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('frequency', models.CharField(choices=[('FIVE', '5 Years'), ('THREEPLUS', '3 times a year'), ('GA', 'Grant Announcement'), ('ONE', 'Annually'), ('ALWAYS', 'Frequently'), ('ANYTIME', 'Submission is possible at any time')], max_length=150)),
                ('avg_funding', models.CharField(max_length=100)),
                ('process_of_funding', models.CharField(choices=[('SP', 'Submission of proposal'), ('RFPLOI', 'RFP - LOI followed by full proposal'), ('UNSOLICITEDRFP', 'Unsolicited & RFP'), ('PROPOSAL', 'Proposal'), ('UNSOLICITED', 'Unsolicited'), ('LOI', 'LOI followed by full proposal')], max_length=200)),
                ('df_funded', models.BooleanField(default=False)),
                ('donors_url', models.URLField()),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
