# Generated by Django 4.0 on 2023-07-21 20:00

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('call_type', models.CharField(max_length=255)),
                ('grant_value', models.CharField(blank=True, max_length=200, null=True)),
                ('advert_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('eligible_countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('concept_note', models.FileField(blank=True, null=True, upload_to='')),
                ('submission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfps', to='donors.donor')),
            ],
        ),
    ]
