# Generated by Django 4.0 on 2023-07-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='applicants',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
